#!/bin/bash

if [[ $1 == "--cn" ]]; then
    echo "Will use cn proxy and Tsinghua tuna apt mirror."
    export cnproxy=https://ghp.ci/
    python3 ./tools/oh-my-tuna.py
else
    unset cnproxy
fi

if ! command -v sudo &> /dev/null
then
    apt update
    apt install -y sudo
fi

sudo apt update
sudo apt install -y zsh git curl vim neovim wget tmux tree iputils-ping

./install-base