#!/bin/bash

# ----- Shell -----

# Oh-my-zsh
export RUNZSH=no
export CHSH=no
sh -c "$(curl -fsSL ${cnproxy}https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# p10k
git clone --depth=1 ${cnproxy}https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
sed -i.bak 's#^ZSH_THEME=\".*\"#ZSH_THEME=\"powerlevel10k/powerlevel10k\"#g' ~/.zshrc

ln -sf "$(pwd)/shell/.p10k.zsh" ~/.p10k.zsh
ln -sf "$(pwd)/shell/.zshalias" ~/.zshalias
ln -sf "$(pwd)/shell/.zshfunc" ~/.zshfunc
touch ~/.zshalias.local
touch ~/.zshfunc.local

cat shell/.zshrc >> ~/.zshrc

# Plugins
git clone ${cnproxy}https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone ${cnproxy}https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
sed -i.bak 's/^plugins=(\(.*\)/plugins=(zsh-autosuggestions zsh-syntax-highlighting git cp poetry tmux \1/' ~/.zshrc

# ----- VIM (NVIM) -----

mkdir -p ~/.config/nvim
touch ~/.config/nvim/init.vim
echo "set runtimepath^=~/.vim runtimepath+=~/.vim/after" >> ~/.config/nvim/init.vim
echo "let &packpath = &runtimepath" >> ~/.config/nvim/init.vim
echo "source ~/.vimrc" >> ~/.config/nvim/init.vim

# vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs ${cnproxy}https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ -f ~/.vimrc ]; then
    mv ~/.vimrc ~/.vimrc.$(date +%Y%m%d%H%M%S).bak
fi
ln -sf "$(pwd)/vim/.vimrc" ~/.vimrc

# Install vim-plug plugins
vim +PlugInstall +qall

# ----- Tmux -----
git clone ${cnproxy}https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
if [ -f ~/.tmux.conf ]; then
    mv ~/.tmux.conf ~/.tmux.conf.$(date +%Y%m%d%H%M%S).bak
fi
ln -s "$(pwd)/tmux/.tmux.conf" ~/.tmux.conf

# ----- Git -----
echo
git config --global user.name "Juntong Chen"
git config --global user.email "dev@jtchen.io"
git config --global core.editor nvim
git config --global core.pager "less -R"
git config --global core.excludesfile ~/.config/.gitignore_global

mkdir -p ~/.config
ln -s "$(pwd)/git/.gitignore_global" ~/.config/.gitignore_global

# ----- Others -----

echo "" >> ~/.zshrc
echo "export PATH=\$PATH:~/.local/bin" >> ~/.zshrc
echo "eval \"\$(zoxide init zsh)\"" >> ~/.zshrc
curl -sSfL ${cnproxy}https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

mkdir -p ~/.local/bin
ln -s $(which fdfind) ~/.local/bin/fd

chsh -s $(which zsh)
echo "Finished. Please DO NOT move the dotfiles directory, or the symbolic links will be broken."
zsh
