#!/bin/bash

dnf makecache
dnf install -y zsh git curl vim wget tmux

if [ $1 = "--cn" ]
then
    echo "Will use cn proxy."
    export cnproxy=https://ghproxy.com/
else
    unset cnproxy
fi

./install-base